import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const HOST='staging.authservices.satispay.com';const BASE=`https://${HOST}`;const APP_RETURN='https://systemtoolbox.github.io/Tanto-Ci-Vai/?satispay=return';const CALLBACK='https://qdsphfmcibrveygkmyex.supabase.co/functions/v1/satispay-callback?payment_id={uuid}';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json','Cache-Control':'no-store'}});
function b64(bytes:Uint8Array){let out='';for(let i=0;i<bytes.length;i++)out+=String.fromCharCode(bytes[i]);return btoa(out)}
function pemToBytes(pem:string){const clean=pem.replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,'');const raw=atob(clean);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function digest(body:string){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body));return `SHA-256=${b64(new Uint8Array(hash))}`}
const admin=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
let CACHE:any=null;
async function creds(){if(CACHE)return CACHE;const{data,error}=await admin().rpc('get_satispay_credentials_for_service');if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.key_id||!row?.private_key)throw new Error('Satispay Sandbox non ancora attivato');CACHE={keyId:String(row.key_id),privatePem:String(row.private_key)};return CACHE}
async function authHeaders(method:string,path:string,body:string){const c=await creds();const date=new Date().toUTCString();const dg=await digest(body);const message=`(request-target): ${method.toLowerCase()} ${path}\nhost: ${HOST}\ndate: ${date}\ndigest: ${dg}`;const key=await crypto.subtle.importKey('pkcs8',pemToBytes(c.privatePem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(message));return{host:HOST,date,digest:dg,authorization:`Signature keyId="${c.keyId}", algorithm="rsa-sha256", headers="(request-target) host date digest", signature="${b64(new Uint8Array(sig))}"`,'content-type':'application/json',accept:'application/json','x-satispay-devicetype':'ECOMMERCE_PLUGIN','x-satispay-apph':'Kairon Labs Studio','x-satispay-appn':'Tanto Ci Vai','x-satispay-appv':'sandbox-v1'}}
async function sat(method:string,path:string,bodyObject?:unknown,idempotencyKey?:string){const body=bodyObject==null?'':JSON.stringify(bodyObject);const headers:any=await authHeaders(method,path,body);if(idempotencyKey)headers['idempotency-key']=idempotencyKey;const res=await fetch(`${BASE}${path}`,{method,headers,body:body||undefined});const text=await res.text();let data:any;try{data=text?JSON.parse(text):{}}catch{data={raw:text}}if(!res.ok)throw new Error(`Satispay ${res.status}: ${data?.message||text||'errore API'}`);return data}
function statusTimes(status:string){const now=new Date().toISOString();return{accepted_at:status==='ACCEPTED'?now:null,cancelled_at:status==='CANCELED'?now:null}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('Authorization')||'';const userClient=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')!,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const{data:{user},error:userErr}=await userClient.auth.getUser();if(userErr||!user)return json({error:'Unauthorized'},401);const body=await req.json().catch(()=>({}));const action=String(body?.action||'');if(action==='health'){try{await creds();return json({ok:true,sandbox:true,configured:true})}catch{return json({ok:true,sandbox:true,configured:false})}}
if(action==='test_auth'){const data=await sat('POST','/wally-services/protocol/tests/signature',{});return json({ok:true,sandbox:true,role:data?.authentication_key?.role||data?.role||null})}
if(action==='create'){const amount=Math.round(Number(body?.amount_unit||0));if(!Number.isInteger(amount)||amount<1||amount>100000)return json({error:'Importo non valido'},400);const orderRef=String(body?.order_ref||`TCV-${Date.now()}`).slice(0,50);const payment=await sat('POST','/g_business/v1/payments',{flow:'MATCH_CODE',amount_unit:amount,currency:'EUR',external_code:orderRef,callback_url:CALLBACK,redirect_url:APP_RETURN,metadata:{tcv_user_id:user.id,tcv_order_ref:orderRef,environment:'sandbox'}},orderRef);const status=String(payment.status||'PENDING');const{error:saveErr}=await admin().from('satispay_payments').upsert({user_id:user.id,satispay_payment_id:String(payment.id),order_ref:orderRef,amount_unit:amount,currency:'EUR',status,sandbox:true,updated_at:new Date().toISOString(),...statusTimes(status)},{onConflict:'satispay_payment_id'});if(saveErr)throw saveErr;return json({ok:true,sandbox:true,id:payment.id,status,redirect_url:payment.redirect_url,code_identifier:payment.code_identifier||null,order_ref:orderRef})}
if(action==='get'){const id=String(body?.payment_id||'').trim();if(!id||id.length>80)return json({error:'Payment id non valido'},400);const{data:owned,error:ownedErr}=await admin().from('satispay_payments').select('satispay_payment_id').eq('satispay_payment_id',id).eq('user_id',user.id).maybeSingle();if(ownedErr)throw ownedErr;if(!owned)return json({error:'Pagamento non trovato'},404);const payment=await sat('GET',`/g_business/v1/payments/${encodeURIComponent(id)}`);const status=String(payment.status||'PENDING');const{error:updateErr}=await admin().from('satispay_payments').update({status,updated_at:new Date().toISOString(),...statusTimes(status)}).eq('satispay_payment_id',id);if(updateErr)throw updateErr;return json({ok:true,sandbox:true,id:payment.id,status,amount_unit:payment.amount_unit,currency:payment.currency,external_code:payment.external_code||null})}
return json({error:'Azione non valida'},400)}catch(e){console.error('satispay-api fatal',String((e as any)?.message||e));return json({error:String((e as any)?.message||e)},500)}});
