from pathlib import Path

p = Path('presentazione.html')
s = p.read_text(encoding='utf-8')

old_hero = '''<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="tag">Pensato per i piccoli paesi</span><h1>Una mano concreta, <span class="gradient">vicino a casa.</span></h1><p class="lead">Spesa, farmacia, pacchi e piccole commissioni. Tanto Ci Vai mette in contatto chi ha bisogno di una mano con chi può fare quella commissione nella stessa zona.</p><div class="hero-actions"><a class="btn btn-primary" href="./">Prova Tanto Ci Vai →</a><a class="btn btn-soft" href="#come">Scopri come funziona</a></div><div class="micro">Servizio indipendente · pensato per comuni, frazioni e zone poco servite</div></div><div class="phone-stage"><div class="glow"></div><div class="floating f1"><b>4 servizi</b>Spesa · Farmacia<br>Pacco · Altro</div><div class="phone"><div class="phone-screen"><video autoplay muted loop playsinline poster="assets/tcv-splash-logo.jpg"><source src="assets/tcv-welcome-5_5s.mp4" type="video/mp4"></video></div></div><div class="floating f2"><b>GPS + mappa</b>Ritiro e consegna<br>con punti precisi</div></div></div></section>'''

new_hero = '''<section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="tag">Pensato per i piccoli paesi</span><h1>Una mano concreta, <span class="gradient">vicino a casa.</span></h1><p class="lead">Spesa, farmacia, pacchi e piccole commissioni. Tanto Ci Vai mette in contatto chi ha bisogno di una mano con chi può fare quella commissione nella stessa zona.</p><div class="hero-actions"><a class="btn btn-primary" href="./">Prova Tanto Ci Vai →</a><a class="btn btn-soft" href="#come">Scopri come funziona</a></div><div class="micro">Servizio indipendente · pensato per comuni, frazioni e zone poco servite</div></div><div class="logo-stage"><div class="logo-orbit"></div><img src="assets/tcv-splash-logo.jpg" alt="Tanto Ci Vai"><div class="logo-caption"><b>Tanto Ci Vai</b><span>Una rete locale. Un aiuto concreto.</span></div></div></div></section>'''

old_cta = '''<section class="cta"><div class="wrap"><div class="cta-box"><h2>Partiamo dal territorio.<br>Poi vediamo fin dove può arrivare.</h2><p>Il primo obiettivo è semplice: creare un servizio utile, affidabile e facile da usare nei piccoli centri. Il modo migliore per capirne il valore è provarlo sul campo.</p><div class="cta-actions"><a class="btn btn-primary" href="./">Apri Tanto Ci Vai →</a><a class="btn btn-soft" href="#top">Torna all'inizio</a></div></div></div></section>'''

new_cta = '''<section class="green-impact"><div class="wrap"><div class="green-shell"><div class="green-kicker">UN CIRCOLO VIRTUOSO PER IL TERRITORIO</div><h2>Più aiuto alle persone.<br><span>Più valore che resta vicino a casa.</span></h2><p class="green-lead">Tanto Ci Vai non serve solo a consegnare qualcosa. Può trasformare piccoli spostamenti quotidiani in un beneficio concreto per cittadini, persone fragili e ambiente.</p><div class="impact-grid"><article class="impact-card"><div class="impact-icon">€</div><div><h3>Entrate extra per i cittadini</h3><p>Chi è disponibile può svolgere commissioni occasionali e ricevere un compenso. Il limite fiscale dei 5.000 € va valutato in base all'inquadramento concreto dell'attività e non rappresenta automaticamente una soglia esente per ogni caso.</p></div></article><article class="impact-card"><div class="impact-icon">♥</div><div><h3>Aiuto concreto a chi ne ha bisogno</h3><p>Anziani, persone con difficoltà di movimento, chi non guida o vive lontano dai servizi può ricevere una mano per le necessità di tutti i giorni.</p></div></article><article class="impact-card"><div class="impact-icon">🍃</div><div><h3>Meno auto, meno spostamenti inutili</h3><p>Se una persona deve già andare in farmacia, al supermercato o in paese, può abbinare una commissione: meno viaggi separati e potenzialmente meno CO₂.</p></div></article><article class="impact-card"><div class="impact-icon">⌂</div><div><h3>Più valore locale</h3><p>Un servizio pensato per paesi, frazioni e zone collinari, dove le grandi piattaforme spesso non arrivano o non sono sostenibili.</p></div></article></div><div class="green-actions"><a class="green-main" href="./">🍃 Apri Tanto Ci Vai →</a><a class="green-soft" href="#come">Scopri come funziona →</a></div></div></div></section>'''

if old_hero not in s:
    raise SystemExit('hero block not found')
if old_cta not in s:
    raise SystemExit('cta block not found')

s = s.replace(old_hero, new_hero, 1)
s = s.replace(old_cta, new_cta, 1)

extra_css = '''
.logo-stage{position:relative;min-height:540px;display:flex;flex-direction:column;align-items:center;justify-content:center;isolation:isolate}.logo-orbit{position:absolute;width:430px;height:430px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.9) 0 35%,rgba(8,205,176,.20) 48%,rgba(11,102,255,.14) 64%,transparent 72%);filter:blur(2px);z-index:-1}.logo-stage img{width:min(310px,68vw);aspect-ratio:1;border-radius:72px;object-fit:cover;box-shadow:0 36px 80px rgba(7,26,61,.22),0 0 0 14px rgba(255,255,255,.7)}.logo-caption{text-align:center;margin-top:30px}.logo-caption b{display:block;font-size:28px;letter-spacing:-.045em}.logo-caption span{display:block;color:#64728b;margin-top:6px;font-size:14px;font-weight:750}
.green-impact{padding:92px 0;background:linear-gradient(180deg,#f4f8fd 0%,#effbea 12%,#dff7d7 100%);position:relative;overflow:hidden}.green-impact:before,.green-impact:after{content:"";position:absolute;border-radius:50%;filter:blur(0);pointer-events:none}.green-impact:before{width:480px;height:480px;left:-240px;bottom:-260px;background:radial-gradient(circle,#86d95b 0%,rgba(134,217,91,.18) 55%,transparent 72%)}.green-impact:after{width:430px;height:430px;right:-220px;top:-170px;background:radial-gradient(circle,#17b67f 0%,rgba(23,182,127,.15) 55%,transparent 72%)}.green-shell{position:relative;overflow:hidden;border-radius:42px;padding:58px;background:linear-gradient(145deg,#087c65 0%,#0aa575 42%,#63c83f 115%);color:#fff;box-shadow:0 34px 90px rgba(18,111,73,.24)}.green-shell:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 84% 12%,rgba(255,255,255,.18),transparent 23%),radial-gradient(circle at 12% 94%,rgba(210,255,160,.18),transparent 27%);pointer-events:none}.green-kicker{position:relative;font-size:12px;font-weight:950;letter-spacing:.14em;color:#d9ffc9}.green-shell h2{position:relative;font-size:clamp(42px,6vw,68px);line-height:.98;letter-spacing:-.055em;margin:12px 0 18px;max-width:900px}.green-shell h2 span{color:#d5ff70}.green-lead{position:relative;max-width:820px;font-size:18px;line-height:1.65;color:rgba(255,255,255,.9)}.impact-grid{position:relative;display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:34px}.impact-card{display:grid;grid-template-columns:64px 1fr;gap:18px;align-items:start;padding:23px;background:rgba(255,255,255,.94);color:#123b2f;border:1px solid rgba(255,255,255,.65);border-radius:25px;box-shadow:0 12px 32px rgba(0,82,53,.12)}.impact-icon{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#1b9c50,#77cf3a);color:#fff;font-size:27px;font-weight:1000;box-shadow:0 9px 20px rgba(27,156,80,.2)}.impact-card h3{margin:1px 0 7px;font-size:20px;letter-spacing:-.03em;color:#17743f}.impact-card p{margin:0;font-size:14px;line-height:1.55;color:#4f665d}.green-actions{position:relative;display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.green-main,.green-soft{display:inline-flex;align-items:center;justify-content:center;padding:16px 22px;border-radius:17px;font-weight:950}.green-main{background:#fff;color:#168343;box-shadow:0 10px 25px rgba(0,72,43,.16)}.green-soft{color:#fff;border:1px solid rgba(255,255,255,.32);background:rgba(255,255,255,.10)}
@media(max-width:900px){.logo-stage{min-height:390px}.logo-stage img{width:min(260px,62vw);border-radius:58px}.impact-grid{grid-template-columns:1fr}.green-shell{padding:42px 30px}}
@media(max-width:560px){.logo-stage{min-height:330px}.logo-stage img{width:210px;border-radius:48px;box-shadow:0 24px 55px rgba(7,26,61,.18),0 0 0 9px rgba(255,255,255,.72)}.logo-caption{margin-top:22px}.logo-caption b{font-size:23px}.green-impact{padding:58px 0}.green-shell{padding:34px 20px;border-radius:30px}.green-shell h2{font-size:39px}.green-lead{font-size:16px}.impact-card{grid-template-columns:52px 1fr;padding:18px;gap:13px}.impact-icon{width:48px;height:48px;font-size:23px}.impact-card h3{font-size:18px}.green-actions{display:grid}.green-main,.green-soft{width:100%}}
'''

s = s.replace('</style>', extra_css + '\n</style>', 1)
p.write_text(s, encoding='utf-8')
print('presentazione.html updated')
