import { createClient } from 'npm:@supabase/supabase-js@2.95.0';
const HOST='staging.authservices.satispay.com';const BASE=`https://${HOST}`;
function b64(bytes:Uint8Array){let out='';for(let i=0;i<bytes.length;i++)out+=String.fromCharCode(bytes[i]);return btoa(out)}
function pemToBytes(pem:string){const clean=pem.replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,'');const raw=atob(clean);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
const admin=()=>createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false,autoRefreshToken:false}});
async function getCreds(){const{data,error}=await admin().rpc('get_satispay_credentials_for_service');if(error)throw error;const row=Array.isArray(data)?data[0]:data;if(!row?.key_id||!row?.private_key)throw new Error('Satispay credentials missing');return{keyId:String(row.key_id),privatePem:String(row.private_key)}}
async function getPayment(paymentId:string){const c=await getCreds();const path=`/g_business/v1/payments/${encodeURIComponent(paymentId)}`;const body='';const digestRaw=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(body));const digest=`SHA-256=${b64(new Uint8Array(digestRaw))}`;const date=new Date().toUTCString();const message=`(request-target): get ${path}\nhost: ${HOST}\ndate: ${date}\ndigest: ${digest}`;const key=await crypto.subtle.importKey('pkcs8',pemToBytes(c.privatePem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(message));const authorization=`Signature keyId="${c.keyId}", algorithm="rsa-sha256", headers="(request-target) host date digest", signature="${b64(new Uint8Array(signed))}"`;const res=await fetch(`${BASE}${path}`,{headers:{host:HOST,date,digest,authorization,accept:'application/json'}});const text=await res.text();if(!res.ok)throw new Error(`Satispay callback GET ${res.status}: ${text}`);return JSON.parse(text)}
function timePatch(status:string){const now=new Date().toISOString(),p:any={status,updated_at:now};if(status==='AUTHORIZED')p.authorized_at=now;if(status==='ACCEPTED'){p.accepted_at=now;p.captured_at=now}if(status==='CANCELED')p.cancelled_at=now;return p}
Deno.serve(async(req)=>{if(req.method!=='GET')return new Response('Method not allowed',{status:405});try{const paymentId=new URL(req.url).searchParams.get('payment_id')||'';if(!paymentId)return new Response('Missing payment_id',{status:400});const payment=await getPayment(paymentId);const status=String(payment.status||'PENDING').toUpperCase();const db=admin();const{data:tracked,error:trackErr}=await db.from('satispay_payments').select('*').eq('satispay_payment_id',paymentId).maybeSingle();if(trackErr)throw trackErr;if(!tracked)return new Response('ok',{status:200});const{error}=await db.from('satispay_payments').update(timePatch(status)).eq('satispay_payment_id',paymentId);if(error)throw error;if(tracked.consegna_id){const{data:d,error:dErr}=await db.from('consegne').select('id,app_fee_status,rider_fund_lock_status,payment_state').eq('id',tracked.consegna_id).maybeSingle();if(dErr)throw dErr;if(d){let app=String(d.app_fee_status||''),hold=String(d.rider_fund_lock_status||''),state=String(d.payment_state||'PAYMENT_REQUIRED');if(tracked.payment_kind==='APP_FEE')app=status;if(tracked.payment_kind==='RIDER_FUND_LOCK')hold=status;if(app==='ACCEPTED'&&hold==='AUTHORIZED')state='READY';else if(app==='CANCELED')state='FEE_CANCELED';else if(hold==='CANCELED')state='HOLD_CANCELED';else if(app==='ACCEPTED')state='HOLD_PENDING';await db.from('consegne').update({app_fee_status:app||null,rider_fund_lock_status:hold||null,payment_state:state}).eq('id',tracked.consegna_id)}}console.log('SATISPAY_CALLBACK_SYNC',JSON.stringify({id:payment.id,status,kind:tracked.payment_kind,delivery:tracked.consegna_id}));return new Response('ok',{status:200,headers:{'cache-control':'no-store'}})}catch(e){console.error('satispay-callback fatal',String((e as any)?.message||e));return new Response('callback error',{status:500})}});
